### ISSUE TITLE
Coinbase API changes:

### ISSUE THREAD

**Issue by Varmetric** [DigitalRuby/ExchangeSharp#810]
As of August 1, the Coinbase API has changed and requires an authenticated connection. Obviously this API no longer works with Coinbase

https://docs.cloud.coinbase.com/exchange/docs/websocket-auth

**Comment by BobDeCuir** [comment]
While I don't agree with Coinbase's decision to require authentication on Level2 requests, I'm surprised this hasn't come up before. This is indeed problematic for ExchangeSharp web requests, because all of the socket APIs are behind sealed and private classes/calls which cannot be overridden. Even the ClientWebSocketImplementation (defaults to System.Net) is private, so there's not much point allowing a different implementation that can't be changed. 

For Coinbase Orderbook sockets, both the connect and channel request must be with authentication headers, which can't be set from the Coinbase Exchange API directly (or indirectly for that matter.) This will require rethinking the ClientWebSocket API implementation.

**Comment by BobDeCuir** [comment]
Working on V2 Coinbase support at this very moment. Thank you.

**Comment by O-Mutt** [comment]
@BobDeCuir i don't see any active branches from you and am interested in the new coinbase impl and would love to help. Have you made any substantial progress?

**Comment by BobDeCuir** [comment]
What a wild ride it has been...
		 
To date, there are FIVE different APIs being offered by Coinbase:
	1) The original V1  - "https://exchange.coinbase.com"
	2) CoinBase Pro - "https://api.pro.coinbase.com"
        3) Advanced Trade V2 - "https://api.coinbase.com/v2"
	4) The next gen which they are in the process of converting to but have yet to document
	5) The FIX protocol used extensively by banking, but no one else uses

There are also THREE Socket Feeds
	1) The Original V1 - "wss://ws-feed.exchange.coinbase.com"
	2) Coinbase Pro - "wss://ws-feed.pro.coinbase.com"
	3) Advanced Trade V2 - "wss://advanced-trade-ws.coinbase.com"

But wait, there's more...

Many of these separate APIs have different Versions (especially Advanced Trade), which change the JSON return data for many calls.  Also, if you've transitioned from the original Coinbase site to Pro, then to Advanced Trade, your trade history remains, but is
returned by the API in different formats depending on the origin. This makes parsing a nightmare.

And the hits keep on coming...

If you created an API Key from the original V1 Coinbase, it still works... sort of. The original V1 API is being depreciated, as are most of the Pro APIs. On their site you can specify which API/Version the key is being used for. You can "Upgrade" this to a later version (or latest Advanced Trade) but this is a one-time process and you cannot revert backwards. Most (not all) of the "Public" APIs of Coinbase Pro still work - for now. There are fewer Public APIs (not requiring an API Key) with Advanced Trade.

Advanced Trade Errata...

Pagination is returned for most Get calls as an element in a JArray. In Pro, the pagination was returned in the Response Header. Not a big deal, really, just different.

All calls must be signed, with few exceptions.

Advanced Trade is unique due to the obfuscating reliance on "Account Ids" (which is ridiculous IMO). The Client/Customer/User belonging to any given API Key does not have a single Account Id. They have a separate AccountId for every coin/currency that Coinbase supports. Additional AccountIds can created/deleted for each supported coin. 

An AccountId is required when retrieving any history. You want to see all trades for "BTC", for example? Good luck. First you need to know the AccountId. Since there are dozens and possibly hundreds of AccountIds, retrieving these is a separate API call - which is paginated at 23 records, so it requires many, many round trips. Then many, many more round trips to retrieve the order history for each AccountId (which is also paginated). As noted above, this data comes back in different formats depending on the origin of the trade order (i.e. original site, pro, advanced trade, etc.)

My guess why Coinbase has all these AccountIds is to separate Wallets for payments/payouts. This might be beneficial in some outlying use cases where "BTC" payments should be separated for different products/services. But in their haste to add such feature creep, they neglected to support simple queries like all orders, all "BTC-USD" trades, or even all "BTC" accounts. 

------

Sifting through this mess was both time-consuming and frustrating. None of this history/change is well documented. Their support is worse than non-existent. 

Still, I like the Coinbase Exchange, and have used it for USD purchases of coins for over a decade. So I will be supporting their latest Advanced Trade API - for what it's worth.

Changes:

Gone are the V1 and Pro support.
Forget about FIX.
Support only latest Advanced Trade API (with silly Wallets)
Sign all calls, as required.
Correctly format trade histories.
Support new pagination where required.
Cache AccountIds locally to eliminate unnecessary round trips (this is problematic if new Ids are created/deleted, oh well..)
Correctly fail when executed Public API calls that require an API Key which isn't set (this applies mostly to sockets).

I have most of this done, but there are a few APIs I need to test that I don't use in my own software. I'll update when this is completed.

**Comment by O-Mutt** [comment]
> I have most of this done, but there are a few APIs I need to test that I don't use in my own software. I'll update when this is completed.
Is there somewhere that you are "keeping" this? Your fork has no active branches and it is not totally clear what this looks like for you.

**Comment by O-Mutt** [comment]
> @O-Mutt 
> 
> Been working on it. I target C#12 locally so had to do some revision when compiling from the master branch. Most of the time has been spent switching between V2 and V3 and determining when to use where. (The changes in their APIs are all over the place with very little consistency.)
> 
> Status:
> Still finishing sockets. These required a near complete rewrite, and I didn’t want to deviate far from the base code. Should be completed by this weekend – but I’m leaving them blank in my fork until I’m satisfied. 
> The PlaceOrder and Withdrawal calls have yet to be tested – so I’m also leaving them blank on my fork for now.
> I’m still not happy with the Transaction Parsing for legacy stuff, and am unsure if it is really needed. Seems adequate for now.
> 
> I’ve pushed the ExchangeCoinbaseAPI.cs file and it compiles if you want to take a look. I won’t be doing a pull request until everything is finished and fully tested. Hopefully by Monday.
> 
> Cheers.
> 

Solid check in. I have a team that is more than willing to assist if there is anything that we can help with. Fwiw I held off on moving forward with my branch for the time being so we didn't duplicate efforts

**Comment by BobDeCuir** [comment]
@O-Mutt ,

Thank you. Actually, I could use some help.

For Placing Orders, the V2 API was having you PlaceBuy, CommitBuy, PlaceSell, Commitsell, and this mess was fairly well documented (if obtuse). This is now officially depreciated as of Nov 30 in favor of V3. But the V3 is missing documentation details and there are no examples – only an endpoint. 

V2 Docs: https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/api-buys
V3 Docs: https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_postorder

As stated in the V3 docs, “Create an order with a specified product_id (asset-pair), side (buy/sell), etc.” Great! What the hell is “etc”? They don’t say.

Also, as best I can deduce, you’re supposed to pass an additional “BODY PARAMS” (Payload) for the “order configuration” of (and I’m guessing here)

"order_configuration": {
    "market_market_ioc": {
      "quote_size": "10.00",
      "base_size": "0.001"
    },
    "limit_limit_gtc": {
      "base_size": "0.001",
      "limit_price": "10000.00",
      "post_only": false
    },
    "limit_limit_gtd": {
      "base_size": "0.001",
      "limit_price": "10000.00",
      "end_time": "2021-05-31T09:59:59Z",
      "post_only": false
    },
    "stop_limit_stop_limit_gtc": {
      "base_size": "0.001",
      "limit_price": "10000.00",
      "stop_price": "20000.00",
      "stop_direction": "UNKNOWN_STOP_DIRECTION"
    },
    "stop_limit_stop_limit_gtd": {
      "base_size": 0.001,
      "limit_price": "10000.00",
      "stop_price": "20000.00",
      "end_time": "2021-05-31T09:59:59Z",
      "stop_direction": "UNKNOWN_STOP_DIRECTION"
    }
  }

I’m also guessing these are exclusive in the "configuration", but the result codes from their result examples suggest they are not. I’ve not been able to successfully test any of this.

If you are available and amenable, and you can take over this one function, I can finish up the sockets implementations much faster.

Your thoughts?

**Comment by BobDeCuir** [comment]
Create Pull Request on 12/03/1023.

Awaiting confirmation.
